# Generated by Django 3.1.7 on 2021-03-31 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('time_to_die', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.CreateModel(
            name='Requisitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', max_length=6)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('active_status', models.BooleanField(default=True)),
                ('review', models.BooleanField(blank=True, null=True)),
                ('recovery', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('requisitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_requisitions', to='helpdesk.requisitions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
