# Generated by Django 3.1.7 on 2021-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitions',
            name='status',
            field=models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=6),
        ),
    ]
